### ISSUE TITLE
Reauthorize BTF pipeline

### ISSUE THREAD

**Issue by jawrainey** [ideafast/middleware-services#60]
### Problem

Recent dev deployment run of the BTF pipeline resulted in:

> 2021-03-31 01:02:22 [15] [data_transfer.lib.byteflies:ERROR] GET Exception to {URL}/recordings/{UUID} 
Traceback (most recent call last):
  File "/app/data_transfer/lib/byteflies.py", line 150, in __get_response
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: {URL}/recordings/{UUID} 

This is likely because BTF uses one object that shared authorisation and the pipeline may run for longer than the pre-defined 1-hour authroisation limit. Therefore we need to modify [the following](https://github.com/ideafast/middleware-services/blob/master/data_transfer/devices/byteflies.py#L63-L75) such that any time a request is made that tokens will be regenerated if needed. 

### Potential solution

We could modify each method (`download_file` and `download_metadata`) to call `authenticate` before it performs logic to ensure if a token has expired that a new one will be generated? I propose that we add a datetime to the constructor of the Byteflies class, then add a new method to do the auth to make it explict as below. We could of course put this logic in `authenticate` if prefered.

```python

def __reauthenticate(self):
    if self.token_created_timestamp <= 60_mins_ago:
        self.authenticate()
``` 

If we go with this appraoch, we can then test this by calling a method that requires authentication (e.g., `download_file`), reassign `self.token_created_timestamp` to 80 mins and verify that the token is different in `self.session`.

**Comment by davidverweij** [comment]
How about us running multiple BTF pipelines in parallel? Does parallel authentication invalidate another one? I did a quick test with Postman, and it seems that the tokens remain valid for the defined limit; even though additional tokens are requested. In that case I think your suggestion seems good. 

I do, however, like your implmentation for [dmpy](https://github.com/ideafast/dmpy/blob/32ebadcf75f42a32296ff233b08e54c704f6620f/dmpy/client.py#L109-L112) (which I also applied for [the UCAM service](https://github.com/ideafast/middleware-services/blob/81750fb479a8a5a83f73e82c7340244185638c0f/data_transfer/services/ucam.py#L60)), where  the authorisation token is a returned value by a method - such as you indicate above. 

In order to achieve that structure, the ByteFlies object needs to handle any requests - rather than passing the session object to the method as currently. I've done this for the [UCAM service](https://github.com/ideafast/middleware-services/blob/81750fb479a8a5a83f73e82c7340244185638c0f/data_transfer/services/ucam.py#L55-L74) - for the BTF this would could look something like:

```python
class ByteFlies:
    def get(self, url:str) -> str:
        headers = {"Authorization": f"Bearer {self.__access_token()}"}
        try:
            # get request
            return result
        except Exception:
            # error
```
And for any method that required a `session` object, we could pass the reference to this method. See example below. We can't pass the ByteFlies object as it are its own methods that require auth. Alternatively, we could create a subclass that can be passed.

```python
all_records = byteflies_api.get_list( self.get , ...  )
```
```python
def get_list(get_url: Callable) -> List[dict]:
    # ...
    get_url("url/get/btf/recordings/")
```

**Thoughts?** - I haven't tested this yet, nor have experience with passing a callable - so any thoughts are welcome.

**Comment by jawrainey** [comment]
Sounds great, although you could move `get` to `byteflies_api` as we're only going to being passing it to all methods in `byteflies_api`? Would simplify `ByteFlies` class and use of the lib too
